### ISSUE TITLE
fnf_converter.py exportAsOsz, exportOsuFile, getScrollSpeed, and others

### ISSUE THREAD

**Issue by MikeM3nia** [Corne2Plum3/fnf2osumania#26]
So. When i was gonna export my .osz file, when its somewhere at like, 70% or so, i get an error like this

 

Traceback (most recent call last):
  File "fnf_converter.py", line 569, in exportAsOsz
  File "fnf_converter.py", line 79, in exportOsuFile
  File "fnf_converter.py", line 345, in getScrollSpeed
  File "json\__init__.py", line 348, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value:
i'd be really happy if you helped me with this issue! would make my day honestly.

![eb92f8c9515521c74c886807f898333e](https://user-images.githubusercontent.com/105606047/168490002-48a23439-1f3f-4fbc-ba73-5a3a3f4a5500.png)
 9562
![eb92f8c9515521c74c886807f898333e](https://user-images.githubusercontent.com/105606047/168490041-f88eff0a-03ad-4072-8898-16b6fb79d228.png)

and yes, i used 1.1.6

i used Windows 10

i used the python file

I used basically all the files that you told me and the other people to use

Oh. right, if you'd wanna reach out to me, i'll always be on discord.
Username/Tag: MikeMania (Insert Tag Here)

Thats about all. hope you'll reach out to me on discord or just on github

**Comment by Corne2Plum3** [comment]
Can you tell me which mod and song you used please?

**Comment by MikeM3nia** [comment]
I used the incident 012F mod, aka the hank demo mod, gunpowder, difficulty hard, tho the original chart of gunpowder was an SM file, but i somehow managed to change it into a JSON file

**Comment by Corne2Plum3** [comment]
ok I'll check that once I'll have free time

**Comment by Marcos875433** [comment]
> I used the incident 012F mod, aka the hank demo mod, gunpowder, difficulty hard, tho the original chart of gunpowder was an SM file, but i somehow managed to change it into a JSON file

The SM file that you mention is on assets/songs/gunpowder/gunfight-hard.sm and isn't the actual fnf chart, the real chart is on assets/data/gunpowder/gunpowder-hard.json, the sm file is actually a StepMania song file, I think is there because I've seen some charters making the chart on a stepmania charter and then converting the chart to a fnf one

https://user-images.githubusercontent.com/58754180/169449188-c3f97bff-250c-46ed-a334-5d4bc880ad34.mp4

**Comment by Marcos875433** [comment]
>I used the incident 012F mod, aka the hank demo mod, gunpowder, difficulty hard, tho the original chart of gunpowder was an SM file, but i somehow managed to change it into a JSON file

The SM file that you mention is on assets/songs/gunpowder/gunfight-hard.sm and isn't the actual fnf chart, the real chart is on assets/data/gunpowder/gunpowder-hard.json, the sm file is actually a StepMania song file, I think is there because I've seen some charters making the chart on a stepmania charter and then converting the chart to a fnf one

**Comment by MikeM3nia** [comment]
Oh thank you Marcos! I didnt knew honestly

**Comment by Corne2Plum3** [comment]
As @Marcos875433 says, you didn't selected the correct file. The chart file isn't a `.sm` but a `.json` file (how you even bypassed the check because the program should reject the `.sm`? Did you modified config.json?). The fnf charts file aren't in the same folder than the .ogg files:
- Song files are in `assets/songs/<song_name>`
- Chart files are in `assets/data/<song_name>`
